import { MapPin } from "lucide-react";
import { Card, StatTile } from "@/components/ui";
import { PageHead, buttonClass, dangerClass, inputClass } from "@/components/management-ui";
import { createClient } from "@/lib/supabase/server";
import { deleteVillage, saveVillage } from "../management-actions";
export const dynamic="force-dynamic";
export default async function VillagesPage(){
 const db=await createClient(); const [{data:villages},{data:branches}]=await Promise.all([db.from("villages").select("*,branches(name)").order("sort_order"),db.from("branches").select("id,name").eq("enabled",true).order("name")]); const rows=villages??[];
 return <><PageHead title="Village Management" body="Control delivery areas, ordering and village-specific charges shown in the customer app."/>
 <div className="mt-5 grid gap-4 sm:grid-cols-2"><StatTile label="Villages served" value={rows.filter(v=>v.enabled).length} icon="truck"/><StatTile label="Hidden villages" value={rows.filter(v=>!v.enabled).length} icon="alert" accent="warn"/></div>
 <Card className="mt-5 p-5"><h2 className="font-extrabold text-ink">Add village</h2><form action={saveVillage} className="mt-4 grid gap-3 md:grid-cols-5"><input name="name" required placeholder="Village name" className={inputClass}/><select name="branch_id" className={inputClass}><option value="">No branch</option>{(branches??[]).map(b=><option key={b.id} value={b.id}>{b.name}</option>)}</select><input name="delivery_charge" min="0" type="number" placeholder="Default charge" className={inputClass}/><input name="sort_order" min="0" type="number" defaultValue={rows.length+1} className={inputClass}/><label className="flex items-center gap-2 text-[13px]"><input name="enabled" type="checkbox" defaultChecked/> Show in app</label><button className={buttonClass}>Add village</button></form></Card>
 <div className="mt-5 grid gap-3">{rows.map(v=><Card key={v.id} className="p-4"><form action={saveVillage} className="grid items-center gap-3 md:grid-cols-[1.3fr_1fr_.7fr_.45fr_.6fr_auto]"><input type="hidden" name="id" value={v.id}/><div className="flex items-center gap-2"><MapPin className="h-5 w-5 text-brand"/><input name="name" defaultValue={v.name} className={inputClass}/></div><select name="branch_id" defaultValue={v.branch_id??""} className={inputClass}><option value="">No branch</option>{(branches??[]).map(b=><option key={b.id} value={b.id}>{b.name}</option>)}</select><input name="delivery_charge" type="number" min="0" defaultValue={v.delivery_charge??""} placeholder="Global" className={inputClass}/><input name="sort_order" type="number" min="0" defaultValue={v.sort_order} className={inputClass}/><label className="flex items-center gap-2 text-[12px]"><input name="enabled" type="checkbox" defaultChecked={v.enabled}/> Visible</label><button className={buttonClass}>Save</button></form><form action={deleteVillage} className="mt-2 flex justify-end"><input type="hidden" name="id" value={v.id}/><button className={dangerClass}>Delete</button></form></Card>)}</div></>;
}
