export type Locale="en"|"hi"|"mr";
export const normalizeLocale=(value?:string):Locale=>value==="hi"||value==="mr"?value:"en";

const hi:Record<string,string>={
 "Language":"भाषा","Delivery Staff":"डिलीवरी स्टाफ","Sign in to view your assigned orders.":"अपने सौंपे गए ऑर्डर देखने के लिए साइन इन करें।",
 "Staff email":"स्टाफ ईमेल","Password":"पासवर्ड","Your password":"अपना पासवर्ड","SIGN IN":"साइन इन","Signing in...":"साइन इन हो रहा है...","Account access is provided by the plant administrator.":"खाता एक्सेस प्लांट एडमिन द्वारा दिया जाता है।",
 "Assigned":"सौंपे गए","Today":"आज","Delivered":"डिलीवर","My Assigned Orders":"मेरे सौंपे गए ऑर्डर","Only orders assigned to your account are shown.":"केवल आपके खाते को सौंपे गए ऑर्डर दिखाए गए हैं।","No assigned orders":"कोई ऑर्डर सौंपा नहीं गया","New assignments will appear here.":"नए सौंपे गए ऑर्डर यहाँ दिखेंगे।",
 "cans":"कैन","confirmed":"पुष्टि","delivered":"डिलीवर","Call Customer":"ग्राहक को कॉल करें","Open Map":"मैप खोलें","Saved":"सहेजा गया","cash":"नकद","empty cans returned":"खाली कैन लौटाए",
 "Cash Collected":"नकद वसूल","Pending":"बकाया","Pending Cans":"लंबित कैन","Empty Cans Returned":"लौटाए गए खाली कैन","Delivery Photo (optional)":"डिलीवरी फ़ोटो (वैकल्पिक)","Customer Signature (optional)":"ग्राहक हस्ताक्षर (वैकल्पिक)","Delivery notes (optional)":"डिलीवरी नोट्स (वैकल्पिक)","Saving...":"सहेज रहा है...","MARK DELIVERED & SAVE":"डिलीवर मार्क करके सहेजें","Sign out":"साइन आउट"
 ,"Enter your staff email and password.":"अपना स्टाफ ईमेल और पासवर्ड दर्ज करें।","Login failed. Check your email and password.":"लॉगिन विफल। ईमेल और पासवर्ड जाँचें।","This delivery staff account is disabled.":"यह डिलीवरी स्टाफ खाता बंद है।","Session expired. Please login again.":"सत्र समाप्त हो गया। फिर से लॉगिन करें।","Delivery photo must be under 5 MB.":"डिलीवरी फ़ोटो 5 MB से कम होनी चाहिए।","Could not upload delivery photo.":"डिलीवरी फ़ोटो अपलोड नहीं हुई।","Enter the full pending balance or leave cash as zero.":"पूरा बकाया दर्ज करें या नकद शून्य रहने दें।","Returned cans exceed the pending cans.":"लौटाए गए कैन लंबित कैन से अधिक हैं।","Could not complete this delivery.":"डिलीवरी पूरी नहीं की जा सकी।","Delivery saved successfully.":"डिलीवरी सफलतापूर्वक सहेजी गई।"
};
const mr:Record<string,string>={
 "Language":"भाषा","Delivery Staff":"वितरण कर्मचारी","Sign in to view your assigned orders.":"तुम्हाला दिलेल्या ऑर्डर पाहण्यासाठी साइन इन करा.",
 "Staff email":"कर्मचारी ईमेल","Password":"पासवर्ड","Your password":"तुमचा पासवर्ड","SIGN IN":"साइन इन","Signing in...":"साइन इन होत आहे...","Account access is provided by the plant administrator.":"खात्याचा प्रवेश प्लांट अ‍ॅडमिन देतात.",
 "Assigned":"सोपवलेले","Today":"आज","Delivered":"वितरित","My Assigned Orders":"माझे सोपवलेले ऑर्डर","Only orders assigned to your account are shown.":"फक्त तुमच्या खात्याला सोपवलेले ऑर्डर दाखवले आहेत.","No assigned orders":"कोणतेही ऑर्डर सोपवले नाहीत","New assignments will appear here.":"नवीन सोपवलेले ऑर्डर येथे दिसतील.",
 "cans":"कॅन","confirmed":"निश्चित","delivered":"वितरित","Call Customer":"ग्राहकाला कॉल करा","Open Map":"नकाशा उघडा","Saved":"जतन झाले","cash":"रोख","empty cans returned":"रिकामे कॅन परत",
 "Cash Collected":"रोख जमा","Pending":"थकबाकी","Pending Cans":"प्रलंबित कॅन","Empty Cans Returned":"परत आलेले रिकामे कॅन","Delivery Photo (optional)":"वितरण फोटो (ऐच्छिक)","Customer Signature (optional)":"ग्राहकाची सही (ऐच्छिक)","Delivery notes (optional)":"वितरण नोट्स (ऐच्छिक)","Saving...":"जतन होत आहे...","MARK DELIVERED & SAVE":"वितरित नोंदवून जतन करा","Sign out":"साइन आउट"
 ,"Enter your staff email and password.":"कर्मचारी ईमेल आणि पासवर्ड टाका.","Login failed. Check your email and password.":"लॉगिन अयशस्वी. ईमेल आणि पासवर्ड तपासा.","This delivery staff account is disabled.":"हे वितरण कर्मचारी खाते बंद आहे.","Session expired. Please login again.":"सत्र संपले. पुन्हा लॉगिन करा.","Delivery photo must be under 5 MB.":"वितरण फोटो 5 MB पेक्षा कमी असावा.","Could not upload delivery photo.":"वितरण फोटो अपलोड झाला नाही.","Enter the full pending balance or leave cash as zero.":"पूर्ण थकबाकी टाका किंवा रोख शून्य ठेवा.","Returned cans exceed the pending cans.":"परत आलेले कॅन प्रलंबित कॅनपेक्षा जास्त आहेत.","Could not complete this delivery.":"वितरण पूर्ण करता आले नाही.","Delivery saved successfully.":"वितरण यशस्वीरित्या जतन झाले."
};
export const t=(locale:Locale,key:string)=>locale==="hi"?(hi[key]??key):locale==="mr"?(mr[key]??key):key;
