import { Languages, Menu, MessageSquareText, Smartphone } from "lucide-react";
import { PageHead, buttonClass, inputClass } from "@/components/management-ui";
import { Card } from "@/components/ui";
import { createClient } from "@/lib/supabase/server";
import { saveAppLabels } from "./actions";

export const dynamic="force-dynamic";
const groups=[
 {title:"Bottom navigation",icon:Smartphone,fields:[["Home","bottom_home"],["Bookings","bottom_bookings"],["Products","bottom_products"],["Wallet","bottom_wallet"],["Profile","bottom_profile"]]},
 {title:"Side drawer",icon:Menu,fields:[["Profile","drawer_profile"],["Order","drawer_order"],["Bookings","drawer_bookings"],["Wallet","drawer_wallet"],["Support","drawer_support"],["Logout","drawer_logout"]]},
 {title:"Booking & payment screens",icon:Languages,fields:[["Booking form title","booking_form_title"],["Request button","request_order_button"],["Payment title","payment_title"],["Summary heading","payment_summary_heading"],["Confirmed title","booking_confirmed_title"],["Pending title","booking_pending_title"],["Back home button","back_home_button"]]},
 {title:"Other screen titles",icon:Smartphone,fields:[["My Bookings","screen_my_bookings"],["Wallet","screen_wallet"],["Profile","screen_profile"],["Notifications","screen_notifications"],["Support","screen_support"],["All products","screen_all_products"],["Product details","screen_product_details"],["Search","screen_search"]]},
 {title:"Login & registration",icon:Languages,fields:[["Login heading","login_heading"],["Registration heading","register_heading"],["Login subtitle","login_subtitle"],["Registration subtitle","register_subtitle"],["Full name label","full_name_label"],["Mobile label","mobile_label"],["Password label","password_label"],["Login button","login_button"],["Registration button","register_button"],["Already registered text","have_account_text"],["New account text","no_account_text"],["Login link","login_link"],["Create ID link","register_link"]]},
 {title:"Customer messages",icon:MessageSquareText,fields:[["Name required","name_required_error"],["Invalid mobile","mobile_invalid_error"],["Invalid password","password_invalid_error"],["Account exists","account_exists_error"],["Invalid login","invalid_login_error"],["Connection error","connection_error"],["Date required","date_required_error"],["Booking save error","booking_save_error"],["Date unavailable","date_unavailable_error"]]},
] as const;
export default async function AppLabelsPage(){const db=await createClient();const{data}=await db.from("settings").select("app_labels").eq("id",1).single();const labels=(data?.app_labels??{}) as Record<string,string>;return <><PageHead title="App Labels" body="Edit navigation, booking-screen labels and customer-facing validation messages."/><form action={saveAppLabels} className="mt-6 space-y-5"><div className="grid gap-5 xl:grid-cols-2">{groups.map(group=><Card key={group.title} className="p-5"><div className="flex items-center gap-3"><group.icon className="h-6 w-6 text-brand"/><h2 className="font-extrabold text-ink">{group.title}</h2></div><div className="mt-5 grid gap-4 sm:grid-cols-2">{group.fields.map(([label,name])=><label key={name} className="text-[12px] font-bold text-ink">{label}<input name={name} defaultValue={labels[name]} required className={inputClass}/></label>)}</div></Card>)}</div><div className="sticky bottom-4 rounded-2xl border border-line bg-surface/95 p-4 shadow-xl backdrop-blur"><button className={buttonClass}>Save App Labels</button></div></form></>;}
